// Base de données des téléphones simples — source de vérité unique.
//
// Règles de rigueur (le dépôt a un passé de faits périmés devenus fausses
// affirmations publiques) :
//  - Un téléphone n'est listé dans une région que si ses bandes / sa
//    disponibilité y tiennent réellement. Le Nokia 2780 Flip est `america`
//    seulement (pas de B20/B28 européennes) — vérifié le 2026-07-16.
//  - `nav` décrit la navigation RÉELLE, pas « a une puce GPS ».
//  - `trueDumbphone: false` = smartphone simplifié (Android bridé), pas un
//    vrai téléphone simple.
//  - Les prix sont indicatifs et bougent ; ils sont affichés comme approximatifs.

import type { Phone } from "./types";

// Liens marchands sans affiliation : page officielle quand la marque vend en
// direct, sinon une recherche chez un revendeur (qui ne renvoie jamais un 404).
const amzFr = (q: string) => `https://www.amazon.fr/s?k=${encodeURIComponent(q)}`;
const amzCom = (q: string) => `https://www.amazon.com/s?k=${encodeURIComponent(q)}`;

export const PHONES: Phone[] = [
  // ————————————————————————— Vrais téléphones simples + Google Maps (KaiOS)
  {
    id: "nokia-6300-4g",
    brand: "Nokia",
    name: "6300 4G",
    regions: ["europe", "america"],
    formFactor: "candybar",
    os: "kaios",
    trueDumbphone: true,
    nav: "full-maps",
    googleMaps: true,
    priceEur: 65,
    priceUsd: 70,
    blurb: {
      fr: "Le vrai téléphone simple le moins cher qui fait tourner Google Maps. Barre classique, clavier, KaiOS.",
      en: "The cheapest genuine dumbphone that runs Google Maps. Classic candybar, keypad, KaiOS.",
    },
    caveat: {
      fr: "Maps sur KaiOS est lent et basique, et son avenir n'est pas garanti (version figée).",
      en: "Google Maps on KaiOS is sluggish and basic, and its long-term support isn't guaranteed.",
    },
    shops: [
      { region: "europe", label: "Amazon.fr", url: amzFr("Nokia 6300 4G") },
      { region: "america", label: "Amazon.com", url: amzCom("Nokia 6300 4G unlocked") },
    ],
  },
  {
    id: "nokia-8000-4g",
    brand: "Nokia",
    name: "8000 4G",
    regions: ["europe", "america"],
    formFactor: "candybar",
    os: "kaios",
    trueDumbphone: true,
    nav: "full-maps",
    googleMaps: true,
    priceEur: 90,
    priceUsd: 100,
    blurb: {
      fr: "Le grand frère mieux fini du 6300 4G : même KaiOS + Google Maps, plus bel écran et finitions.",
      en: "The nicer-built sibling of the 6300 4G: same KaiOS + Google Maps, better screen and finish.",
    },
    caveat: {
      fr: "Comme tous les KaiOS : navigation lente, avenir de l'appli Maps incertain.",
      en: "Like all KaiOS phones: sluggish navigation, uncertain future for the Maps app.",
    },
    shops: [
      { region: "europe", label: "Amazon.fr", url: amzFr("Nokia 8000 4G") },
      { region: "america", label: "Amazon.com", url: amzCom("Nokia 8000 4G") },
    ],
  },
  {
    id: "nokia-2780-flip",
    brand: "Nokia",
    name: "2780 Flip",
    regions: ["america"],
    formFactor: "flip",
    os: "kaios",
    trueDumbphone: true,
    nav: "full-maps",
    googleMaps: true,
    priceUsd: 90,
    blurb: {
      fr: "Clapet KaiOS avec Google Maps, très répandu en Amérique du Nord.",
      en: "KaiOS flip with Google Maps, widely available in North America.",
    },
    caveat: {
      fr: "Variante US (TA-1420) : ses bandes ne couvrent PAS la France/l'UE (pas de B20/B28). À éviter en Europe.",
      en: "US variant (TA-1420): its bands do NOT cover France/EU (no B20/B28). Avoid in Europe.",
    },
    shops: [{ region: "america", label: "Amazon.com", url: amzCom("Nokia 2780 Flip") }],
  },
  {
    id: "nokia-2760-flip",
    brand: "Nokia",
    name: "2760 Flip",
    regions: ["america"],
    formFactor: "flip",
    os: "kaios",
    trueDumbphone: true,
    nav: "full-maps",
    googleMaps: true,
    priceUsd: 80,
    blurb: {
      fr: "Version plus abordable du 2780 Flip : KaiOS 3.1, Google Maps, sans radio FM ni carte SD.",
      en: "The more affordable 2780 Flip: KaiOS 3.1, Google Maps, but no FM radio or SD card.",
    },
    caveat: {
      fr: "Variante nord-américaine : vérifier les bandes hors USA/Canada.",
      en: "North-American variant: check bands outside the US/Canada.",
    },
    shops: [{ region: "america", label: "Amazon.com", url: amzCom("Nokia 2760 Flip") }],
  },
  {
    id: "tcl-flip-2",
    brand: "TCL",
    name: "Flip 2",
    regions: ["america"],
    formFactor: "flip",
    os: "kaios",
    trueDumbphone: true,
    nav: "full-maps",
    googleMaps: true,
    priceUsd: 60,
    blurb: {
      fr: "L'un des clapets KaiOS + Google Maps les moins chers du marché nord-américain.",
      en: "One of the cheapest KaiOS + Google Maps flips on the North-American market.",
    },
    shops: [{ region: "america", label: "Amazon.com", url: amzCom("TCL Flip 2") }],
  },
  {
    id: "alcatel-go-flip-4",
    brand: "Alcatel",
    name: "Go Flip 4",
    regions: ["america"],
    formFactor: "flip",
    os: "kaios",
    trueDumbphone: true,
    nav: "full-maps",
    googleMaps: true,
    priceUsd: 70,
    blurb: {
      fr: "Clapet KaiOS simple et bon marché avec Google Maps, courant chez les opérateurs US.",
      en: "Simple, cheap KaiOS flip with Google Maps, common on US carriers.",
    },
    shops: [{ region: "america", label: "Amazon.com", url: amzCom("Alcatel Go Flip 4") }],
  },

  // ————————————————————————— Vrais téléphones simples + navigation maison
  {
    id: "light-phone-iii",
    brand: "Light",
    name: "Phone III",
    regions: ["global", "america", "europe"],
    formFactor: "touch",
    os: "proprietary",
    trueDumbphone: true,
    nav: "basic-nav",
    googleMaps: false,
    priceEur: 730,
    priceUsd: 799,
    blurb: {
      fr: "Le téléphone minimaliste emblématique : appli d'itinéraire maison, pas de navigateur, pas de réseaux sociaux.",
      en: "The flagship intentional phone: own Directions app, no browser, no social media.",
    },
    caveat: {
      fr: "Cher, et les nouvelles précommandes n'arrivent qu'à partir de septembre 2026.",
      en: "Expensive, and new pre-orders only ship from September 2026.",
    },
    shops: [{ region: "global", label: "thelightphone.com", url: "https://www.thelightphone.com/" }],
  },
  {
    id: "mudita-kompakt",
    brand: "Mudita",
    name: "Kompakt",
    regions: ["europe", "global"],
    formFactor: "touch",
    os: "proprietary",
    trueDumbphone: true,
    nav: "basic-nav",
    googleMaps: false,
    priceEur: 439,
    priceUsd: 479,
    blurb: {
      fr: "Écran E-Ink apaisant, cartes hors ligne intégrées, plusieurs jours d'autonomie. Marque européenne (Pologne).",
      en: "Calm E-Ink screen, built-in offline maps, multi-day battery. EU (Polish) company.",
    },
    caveat: {
      fr: "Les cartes hors ligne suffisent pour se repérer, mais sans trafic en temps réel.",
      en: "Offline maps are enough to find your way, but there's no live traffic.",
    },
    shops: [{ region: "global", label: "mudita.com", url: "https://mudita.com/products/phones/mudita-kompakt/" }],
  },
  {
    id: "mudita-pure",
    brand: "Mudita",
    name: "Pure",
    regions: ["europe", "global"],
    formFactor: "candybar",
    os: "proprietary",
    trueDumbphone: true,
    nav: "none",
    googleMaps: false,
    priceEur: 369,
    priceUsd: 399,
    blurb: {
      fr: "E-Ink ultra-minimaliste, pensé pour le calme numérique. Appels, SMS, l'essentiel — pas de cartes.",
      en: "Ultra-minimalist E-Ink phone built for digital calm. Calls, texts, essentials — no maps.",
    },
    shops: [{ region: "global", label: "mudita.com", url: "https://mudita.com/products/phones/mudita-pure/" }],
  },

  // ————————————————————————— Vrais téléphones simples : GPS localisation seule
  {
    id: "punkt-mp02",
    brand: "Punkt",
    name: "MP02",
    regions: ["europe", "global"],
    formFactor: "candybar",
    os: "proprietary",
    trueDumbphone: true,
    nav: "location-only",
    googleMaps: false,
    priceEur: 299,
    priceUsd: 329,
    blurb: {
      fr: "Design suisse épuré, 4G, messagerie chiffrée Signal. Conçu pour l'UE (bandes françaises couvertes).",
      en: "Clean Swiss design, 4G, encrypted Signal messaging. Built for the EU (French bands covered).",
    },
    caveat: {
      fr: "A une puce GPS mais AUCUNE carte ni navigation — inutile si vous voulez vous guider.",
      en: "Has a GPS chip but NO maps or navigation — useless if you want turn-by-turn directions.",
    },
    shops: [{ region: "global", label: "punkt.ch", url: "https://www.punkt.ch/en/products/mp02-4g-mobile-phone/" }],
  },
  {
    id: "doro-leva-l10",
    brand: "Doro",
    name: "Leva L10",
    regions: ["europe"],
    formFactor: "candybar",
    os: "feature",
    trueDumbphone: true,
    nav: "location-only",
    googleMaps: false,
    priceEur: 90,
    blurb: {
      fr: "Téléphone simple pour seniors, marque suédoise (UE). Bouton d'assistance qui envoie ta position GPS à des proches.",
      en: "Senior-friendly dumbphone, Swedish (EU) brand. Assistance button sends your GPS location to trusted contacts.",
    },
    caveat: {
      fr: "Le GPS sert à la localisation d'urgence, pas à naviguer : aucune carte à bord.",
      en: "GPS is for emergency location, not navigation: no maps on board.",
    },
    shops: [{ region: "europe", label: "doro.com", url: "https://www.doro.com/" }],
  },
  {
    id: "doro-6880",
    brand: "Doro",
    name: "6880",
    regions: ["europe"],
    formFactor: "flip",
    os: "feature",
    trueDumbphone: true,
    nav: "location-only",
    googleMaps: false,
    priceEur: 100,
    blurb: {
      fr: "Clapet seniors avec grandes touches et bouton d'assistance géolocalisé. Clavier vocal.",
      en: "Senior flip phone with big keys and a location-aware assistance button. Spoken keypad.",
    },
    shops: [{ region: "europe", label: "doro.com", url: "https://www.doro.com/" }],
  },

  // ————————————————————————— Vrais téléphones simples : sans GPS (rappel/UE)
  {
    id: "nokia-2660-flip",
    brand: "Nokia",
    name: "2660 Flip",
    regions: ["europe", "global"],
    formFactor: "flip",
    os: "series30",
    trueDumbphone: true,
    nav: "none",
    googleMaps: false,
    priceEur: 75,
    blurb: {
      fr: "Le clapet Nokia natif UE : bandes correctes, grand écran, très simple. Mais pas d'appli cartes.",
      en: "The EU-native Nokia flip: correct bands, big display, dead simple. But no maps app.",
    },
    shops: [
      { region: "europe", label: "Amazon.fr", url: amzFr("Nokia 2660 Flip") },
      { region: "america", label: "Amazon.com", url: amzCom("Nokia 2660 Flip") },
    ],
  },
  {
    id: "nokia-3210-4g",
    brand: "Nokia",
    name: "3210 4G (2024)",
    regions: ["europe", "global"],
    formFactor: "candybar",
    os: "series30",
    trueDumbphone: true,
    nav: "none",
    googleMaps: false,
    priceEur: 80,
    blurb: {
      fr: "La réédition culte de 2024 : 4G, Snake, autonomie énorme. Nostalgie assumée, sans cartes.",
      en: "The cult 2024 reissue: 4G, Snake, huge battery life. Pure nostalgia, no maps.",
    },
    shops: [
      { region: "europe", label: "Amazon.fr", url: amzFr("Nokia 3210 4G") },
      { region: "america", label: "Amazon.com", url: amzCom("Nokia 3210 4G") },
    ],
  },
  {
    id: "nokia-8210-4g",
    brand: "Nokia",
    name: "8210 4G",
    regions: ["europe", "global"],
    formFactor: "candybar",
    os: "series30",
    trueDumbphone: true,
    nav: "none",
    googleMaps: false,
    priceEur: 70,
    blurb: {
      fr: "Réédition de la barre légendaire, 4G. Robuste, sobre, longue autonomie — pas de navigation.",
      en: "Reissue of the legendary candybar, 4G. Rugged, plain, long battery — no navigation.",
    },
    shops: [{ region: "europe", label: "Amazon.fr", url: amzFr("Nokia 8210 4G") }],
  },
  {
    id: "nokia-6310",
    brand: "Nokia",
    name: "6310 (2024)",
    regions: ["europe", "global"],
    formFactor: "candybar",
    os: "series30",
    trueDumbphone: true,
    nav: "none",
    googleMaps: false,
    priceEur: 65,
    blurb: {
      fr: "Grand écran incurvé, très lisible, boutons francs. Le classique « ça appelle et ça dure ».",
      en: "Large curved, very readable screen, firm buttons. The classic 'it calls and it lasts'.",
    },
    shops: [{ region: "europe", label: "Amazon.fr", url: amzFr("Nokia 6310 2024") }],
  },
  {
    id: "nokia-235-4g",
    brand: "Nokia",
    name: "235 4G",
    regions: ["europe", "global"],
    formFactor: "candybar",
    os: "series30",
    trueDumbphone: true,
    nav: "none",
    googleMaps: false,
    priceEur: 55,
    blurb: {
      fr: "Barre 4G d'entrée de gamme, sobre et fiable. Appels, SMS, radio — rien de plus.",
      en: "Entry-level 4G candybar, plain and reliable. Calls, texts, radio — nothing more.",
    },
    shops: [{ region: "europe", label: "Amazon.fr", url: amzFr("Nokia 235 4G") }],
  },
  {
    id: "nokia-110-4g",
    brand: "Nokia",
    name: "110 4G",
    regions: ["europe", "global"],
    formFactor: "candybar",
    os: "series30",
    trueDumbphone: true,
    nav: "none",
    googleMaps: false,
    priceEur: 35,
    blurb: {
      fr: "Le minimum vital, très bon marché : appels et SMS 4G, lampe torche, radio FM.",
      en: "The bare essentials, very cheap: 4G calls and texts, flashlight, FM radio.",
    },
    shops: [{ region: "europe", label: "Amazon.fr", url: amzFr("Nokia 110 4G") }],
  },
  {
    id: "emporia-simplicity",
    brand: "Emporia",
    name: "Simplicity",
    regions: ["europe"],
    formFactor: "flip",
    os: "feature",
    trueDumbphone: true,
    nav: "none",
    googleMaps: false,
    priceEur: 60,
    blurb: {
      fr: "Marque autrichienne (UE) pour seniors : très grandes touches, son fort, bouton d'urgence.",
      en: "Austrian (EU) senior brand: extra-large keys, loud sound, emergency button.",
    },
    shops: [{ region: "europe", label: "Amazon.fr", url: amzFr("Emporia Simplicity") }],
  },
  {
    id: "gigaset-gl590",
    brand: "Gigaset",
    name: "GL590",
    regions: ["europe"],
    formFactor: "candybar",
    os: "feature",
    trueDumbphone: true,
    nav: "none",
    googleMaps: false,
    priceEur: 55,
    blurb: {
      fr: "Barre allemande (UE) simple et robuste, grandes touches, bouton SOS. Assemblée en Allemagne.",
      en: "Simple, rugged German (EU) candybar, big keys, SOS button. Assembled in Germany.",
    },
    shops: [{ region: "europe", label: "Amazon.fr", url: amzFr("Gigaset GL590") }],
  },
  {
    id: "alcatel-2057",
    brand: "Alcatel",
    name: "2057",
    regions: ["europe", "global"],
    formFactor: "candybar",
    os: "feature",
    trueDumbphone: true,
    nav: "none",
    googleMaps: false,
    priceEur: 30,
    blurb: {
      fr: "L'un des téléphones simples neufs les moins chers. Double SIM, radio, lampe. 2G/3G — vérifier la 4G.",
      en: "One of the cheapest new dumbphones. Dual SIM, radio, torch. 2G/3G — check for 4G.",
    },
    caveat: {
      fr: "Modèle 2G/3G : la 2G ferme en France (mars 2026) — préférez une variante 4G.",
      en: "2G/3G model: 2G is shutting down in France (March 2026) — prefer a 4G variant.",
    },
    shops: [{ region: "europe", label: "Amazon.fr", url: amzFr("Alcatel 2057") }],
  },

  // ————————————————————————— Clapets/robustes nord-américains sans maps
  {
    id: "sonim-xp3plus",
    brand: "Sonim",
    name: "XP3plus",
    regions: ["america"],
    formFactor: "flip",
    os: "kaios",
    trueDumbphone: true,
    nav: "full-maps",
    googleMaps: true,
    priceUsd: 200,
    blurb: {
      fr: "Clapet ultra-robuste (chantier, extérieur), KaiOS avec Google Maps. Étanche, antichoc.",
      en: "Ultra-rugged flip (worksite, outdoors), KaiOS with Google Maps. Waterproof, shockproof.",
    },
    shops: [{ region: "america", label: "Amazon.com", url: amzCom("Sonim XP3plus") }],
  },
  {
    id: "schok-classic-flip",
    brand: "Schok",
    name: "Classic Flip",
    regions: ["america"],
    formFactor: "flip",
    os: "kaios",
    trueDumbphone: true,
    nav: "basic-nav",
    googleMaps: false,
    priceUsd: 50,
    blurb: {
      fr: "Clapet américain très bon marché, KaiOS, avec cartes basiques. Bon budget pour tester.",
      en: "Very cheap US flip, KaiOS, with basic maps. A good budget pick to test the water.",
    },
    caveat: {
      fr: "Support cartes basique et variable selon l'opérateur ; vérifier avant l'achat.",
      en: "Map support is basic and carrier-dependent; verify before buying.",
    },
    shops: [{ region: "america", label: "Amazon.com", url: amzCom("Schok Classic Flip") }],
  },

  // ————————————————————————— Smartphones simplifiés (Google Maps complet)
  {
    id: "doro-8100",
    brand: "Doro",
    name: "8100",
    regions: ["europe", "america"],
    formFactor: "touch",
    os: "android-lite",
    trueDumbphone: false,
    nav: "full-maps",
    googleMaps: true,
    priceEur: 180,
    priceUsd: 200,
    blurb: {
      fr: "Android simplifié (interface EVA) avec Google Maps préinstallé + Play Store + bouton d'assistance GPS. Version FR sur Amazon.fr.",
      en: "Simplified Android (EVA interface) with Google Maps pre-installed + Play Store + GPS assistance button. FR version on Amazon.fr.",
    },
    caveat: {
      fr: "C'est un smartphone simplifié, pas un vrai téléphone simple : l'écran et les applis restent là.",
      en: "It's a simplified smartphone, not a true dumbphone: the screen and apps are still there.",
    },
    shops: [
      { region: "europe", label: "Amazon.fr", url: amzFr("Doro 8100") },
      { region: "america", label: "Amazon.com", url: amzCom("Doro 8100") },
    ],
  },
  {
    id: "minimal-phone",
    brand: "Minimal",
    name: "Phone",
    regions: ["global", "america"],
    formFactor: "qwerty",
    os: "android-lite",
    trueDumbphone: false,
    nav: "full-maps",
    googleMaps: true,
    priceEur: 439,
    priceUsd: 399,
    blurb: {
      fr: "Écran E-Ink + clavier physique QWERTY, sous Android complet avec Play Store. Maps oui, distractions au choix.",
      en: "E-Ink screen + physical QWERTY, running full Android with the Play Store. Maps yes, distractions optional.",
    },
    caveat: {
      fr: "Android complet : la discipline dépend de vous, pas du matériel.",
      en: "Full Android: the discipline is on you, not the hardware.",
    },
    shops: [{ region: "global", label: "minimalcompany.com", url: "https://www.minimalcompany.com/" }],
  },
  {
    id: "wisephone-ii",
    brand: "Wisephone",
    name: "II",
    regions: ["america"],
    formFactor: "touch",
    os: "android-lite",
    trueDumbphone: false,
    nav: "full-maps",
    googleMaps: true,
    priceUsd: 500,
    blurb: {
      fr: "« Le smartphone le plus bête » : matériel Galaxy A15 sous WiseOS verrouillé. Cartes et musique, sans les applis addictives.",
      en: "'The smartest dumb phone': Galaxy A15 hardware under locked-down WiseOS. Maps and music, minus the addictive apps.",
    },
    caveat: {
      fr: "Vendu aux USA ; disponibilité et bandes hors Amérique à vérifier.",
      en: "Sold in the US; availability and bands outside America need checking.",
    },
    shops: [{ region: "america", label: "wisephone.com", url: "https://www.wisephone.com/" }],
  },
  {
    id: "sunbeam-f1",
    brand: "Sunbeam",
    name: "F1",
    regions: ["america"],
    formFactor: "flip",
    os: "proprietary",
    trueDumbphone: true,
    nav: "full-maps",
    googleMaps: false,
    priceUsd: 195,
    blurb: {
      fr: "Clapet à logiciel sur-mesure : tu ajoutes Waze, musique, météo — pas de navigateur ni de réseaux sociaux.",
      en: "Flip with purpose-built software: you add Waze, music, weather — no browser or social media.",
    },
    caveat: {
      fr: "Marché américain (opérateurs US) ; ne convient pas à l'Europe.",
      en: "US market (US carriers); not suitable for Europe.",
    },
    shops: [{ region: "america", label: "sunbeamwireless.com", url: "https://www.sunbeamwireless.com/" }],
  },
  {
    id: "cat-s22-flip",
    brand: "Cat",
    name: "S22 Flip",
    regions: ["america"],
    formFactor: "flip",
    os: "android-lite",
    trueDumbphone: false,
    nav: "full-maps",
    googleMaps: true,
    priceUsd: 180,
    blurb: {
      fr: "Clapet robuste sous Android (écran tactile, Play Store, Google Maps complet). Étanche, antichoc.",
      en: "Rugged flip running Android (touchscreen, Play Store, full Google Maps). Waterproof, shockproof.",
    },
    caveat: {
      fr: "Sous Android : c'est un smartphone déguisé en clapet, pas un vrai téléphone simple.",
      en: "It's Android: a smartphone dressed as a flip, not a true dumbphone.",
    },
    shops: [{ region: "america", label: "Amazon.com", url: amzCom("Cat S22 Flip") }],
  },

  // ————————————————————————— Feature phone tactile (Asie/global)
  {
    id: "xiaomi-qin-f21-pro",
    brand: "Xiaomi (Qin)",
    name: "F21 Pro",
    regions: ["global"],
    formFactor: "touch",
    os: "android-lite",
    trueDumbphone: false,
    nav: "full-maps",
    googleMaps: true,
    priceEur: 100,
    priceUsd: 110,
    blurb: {
      fr: "Mini téléphone tactile sous Android allégé, GPS/A-GPS, applis possibles. Import (global), bandes à vérifier.",
      en: "Tiny touchscreen phone on lightweight Android, GPS/A-GPS, apps possible. Import (global), check bands.",
    },
    caveat: {
      fr: "Import : la compatibilité des bandes 4G FR/UE n'est pas garantie — à vérifier avant d'acheter.",
      en: "Import: FR/EU 4G band compatibility isn't guaranteed — verify before buying.",
    },
    shops: [{ region: "global", label: "AliExpress", url: "https://www.aliexpress.com/w/wholesale-Qin-F21-Pro.html" }],
  },
];
